### ISSUE TITLE
SSDs vs. normal hard disks

### ISSUE THREAD

**Issue by PTRRupprecht** [ClearAnatomics/ClearMap#14]
Dear Christoph,

Related to issue #13 , we also wondered about specific hardware requirements (for TubeMap). Currently, we are using regular hard disks for processing.

However, due to the memmap objects, we imagine that there are a lot of read-and-write processes.

Our question: For the total processing time, is it crucial to have high-speed SSDs, or is the time required for reading and writing negligible compared to the pure processing time (e.g., during binarization or vessel filling) ? Have to compared SSD-based and HDD-based processing?

Best wishes,
Peter

**Comment by nicolasrenier** [comment]
Dear Peter,

Sorry I'm getting into these boards for the first time and checking the messages I can answer. Maybe this is not needed anymore, but might be useful to someone to know this:

- You can use HDD with TubeMap. We have both configuration in the lab. For the most part, HDD perform similarly to SSD because these are not the limiting factor (CPU is). There is only one step where the SSD makes a big difference from the HDD, it is for the stitching of the data with Wobbly Stitcher. On our machine with SSD, stitching a 400Gb dataset (200Gb/Channel) takes about 30 minutes. On the machine with HDD (same configuration otherwise), it takes about 3 to 4h.

Nicolas Renier

**Comment by PTRRupprecht** [comment]
Dear Nicolas, thank you for this note!
