### ISSUE TITLE
how to view result.0.mhd file in imageJ?

### ISSUE THREAD

**Issue by ywang219** [ClearAnatomics/ClearMap#27]
Hi,
after alignment, I opened the result.0.mhd file which appears as following: I also tried to drag it to imageJ which does the same. What is the problem here? Thank you!

ObjectType = Image
NDims = 3
BinaryData = True
BinaryDataByteOrderMSB = False
CompressedData = True
CompressedDataSize = 787716
TransformMatrix = 1 0 0 0 1 0 0 0 1
Offset = 0 0 0
CenterOfRotation = 0 0 0
AnatomicalOrientation = RAI
ElementSpacing = 1 1 1
DimSize = 351 416 7
ElementType = MET_SHORT
ElementDataFile = result.0.zraw

**Comment by SaibotMagd** [comment]
ImageJ got 3 very different versions (ImageJ1, ImageJ2 and Fiji) and a lot of plugins. To load a mhd file you need a particular plugin. But I don't know the name. The easier way will be to download Fiji because it consists a lot of plugins you will need to work with Clearmap, beside the mhd-file plugin. You can download it here for example: 

[https://imagej.net/Fiji/Downloads](https://imagej.net/Fiji/Downloads)


PS: an alternative way to read the files is to convert them to tif-files. This is possible if you use this command:
```
  io.convert_files(ws.filename('resampled_to_auto', extension='npy'), extension='tif',
                 processes=4, verbose=True);
```
If you do that with the "stitched.npy" file you will be able to load very large files in imageJ with the "visual stack" function (File->Import->Bioformats). So you can load files with hundreds of GB even on a somewhat poor pc. ;)
