### ISSUE TITLE
Will there be any fixes for the issues?

### ISSUE THREAD

**Issue by stasys-hub** [ClearAnatomics/ClearMap#41]
Hello Christoph,

I really appreciate the efforts you took to make such a big project publicly available. Since I really would like to use your software package I wanted to ask whether there will be any support? Currently this project looks quite abandoned and a lot people seem to have issues with the package. 
So I just wanted to ask: Will you still work on the project and commit updates?

**Comment by ChristophKirst** [comment]
Hi

Thank you for your comment. We just recently made this second version of ClearMap available and of course are planning to provide fixes and updates. 

Due to me setting up my own lab at UCSF there was unfortunately little time to maintain the software over the last weeks,
i apologize, but the project is certainly not abandoned. 

Software maintenance unfortunately is not necessarily rewarded as much in the scientific community.

In fact, as requests for fixes and help are increasing here and via email, 
we are writing proposals for funding to help us maintain this software on a much more regular basis
and hope this will be successful.

I will also push a few fixes in the next days.

Thank you for understanding.

Christoph
