### ISSUE TITLE
Parameters for the tubeness measure

### ISSUE THREAD

**Issue by saskra** [ClearAnatomics/ClearMap#42]
Just a short question: The gamma parameter in your Frangi filter in the code is slightly different from the one in the documentation and paper - do you expect differences in the results, or is it negligible?

https://github.com/ChristophKirst/ClearMap2/blob/d9c433925716a5e5153d922a4933cec463eff329/ClearMap/ImageProcessing/Differentiation/Hessian.py#L103

https://christophkirst.github.io/ClearMap2Documentation/html/tubemap.html#tube-filtering-and-fifth-binarization

**Comment by ChristophKirst** [comment]
Thanks for noting this.

We used the parameters as stated in the paper, for simplicity i put the default parameter to 1.0 when cleaning up the code
which might not be ideal.

There is certainly a difference (see  Sato et al. Three-dimensional multi-scale line filter for segmentation and visualization of curvilinear structures in medical images, Medical Image Analysis 1998, pp 143--168).

Due to subsequent thresholding and processing the effect might be minor though. However, to reproduce the results in the paper i recommend using the original parameter.
