### ISSUE TITLE
Question about making 3D tiff files for Wobbly stitching

### ISSUE THREAD

**Issue by Shigeaki-Kanatani** [ClearAnatomics/ClearMap#62]
Hi,

This is maybe a silly question, but I would like to ask about data preparation for TubeMap.  
The tile images used in the tutorial of Wobbly stitcher is 3D tiff file, but as far as I know, the Lavision light sheet microscope saves each image separately as 2D tiff files. How do you make 3D tiff files? Is there a tool or nice way to make 3D tiff files for Wobbly stitcher? I noticed that using 3D tiff file format is also very convenient because it reduces the time to handle data.

Thank you for your help in advance.

Best regards,

Shigeaki

**Comment by EdwinHernandezG** [comment]
Let me answer from my experience with TubeMap.

The idea to work with 3D tiff files is mainly because, in the type of acquisition that they use, they generate hundreds of tiles for the brain mosaic.

In fact, in all LaVision microscopes, you can generate single 3D tiles for each tile of your mosaic. In a classical way to save the files, you go Z step, then Color filter, then X step, then Y step, and you let the four small discs on to save all the 2D tiffs.
If you uncheck the first disk, ImSpector will generate one 3D Tiff for your tile and channel.

For generating the 3D Tiffs from the 2D, you can use Fiji or few python lines. [https://stackoverflow.com/questions/47182125/how-to-combine-tif-stacks-in-python](url).

Finally, have in mind that there is an unsolved issue stitching large images that generates black tiles on your final mosaic.

**Comment by Shigeaki-Kanatani** [comment]
Hi Edwin,

Thank you very much for your answer. It is really helpful.
We are converting many 2D tiff files into 3D tiff files by our script, however, this conversion including file transfer takes extremely long time (days). So, it is really nice if LaVision microscope has a option to save data as 3D tiff.

I am wondering if you would describe in detail what you mean 'If you uncheck the first disk'. Is it in 'Autosave settings'>'Advanced settings'>'Standard file names' (Customize)? I would appreciate it if you would give me a hint for this.

Best regards,

Shigeaki

**Comment by EdwinHernandezG** [comment]
In Fig 10 of the supplementary material from the paper. Just check that the first disk is not bright. in the AS column
![SavingSettings](https://user-images.githubusercontent.com/61184296/110821128-112d1200-8290-11eb-8ba5-12cde00682a9.JPG)
Just be sure that your microscope PC has enough RAM to store your tile temporally.

**Comment by Shigeaki-Kanatani** [comment]
Hi Edwin,

Thank you very much! I have never imagined AS disk buttons influence the output format. I will try.
I also want to say thank you again for your replying my previous comments(#56).

Best,

Shigeaki

**Comment by Shigeaki-Kanatani** [comment]
Hi Edwin,

I have tested and we confirm the data is saved in 3D Tiff format. Thank you very much.
The problem is solved, so I close this issue.

Best,

Shigeaki

**Comment by freblisna** [comment]
This is a very helpful thread. Thanks!
